Create setting to remember default notification channel
BenHUET/eveseat-calendar pull request #60
Opened 2021-12-29 00:34 UTC by alkari-verende

This adds a drop-down to the Slack settings in the calendar allowing an administrator to choose a default notification channel. If saved, this channel will be pre-selected when creating a new Operation.
<img width="390" alt="147420461-1ebda0ac-c55d-4d0c-a637-20d65793097c" src="https://user-images.githubusercontent.com/70491080/147616943-394d8a41-f775-4589-9e2c-beebece03ab9.png">
<img width="808" alt="147420469-30a7187f-21f9-4f7a-addd-e802a60ef252" src="https://user-images.githubusercontent.com/70491080/147616946-a78820ae-5572-4f48-8011-92b0ff4e9832.png">

2021-12-29 09:59 UTC, warlof requested changes
simple and definitely useful - if you could make a bit of refactor so it meet with standard ? 👍

2021-12-29 09:59 UTC, warlof commented on src/Http/Controllers/SettingController.php
> +            'slackIntegrations' => $notification_channels,
as per convention, it has to be `slack_integration`

2021-12-29 09:59 UTC, warlof commented on src/Http/Controllers/SettingController.php
> +            $request->slack_integration_default_channel,
should add a validation to ensure input value is valid
https://laravel.com/docs/6.x/validation#quick-writing-the-validation-logic
https://laravel.com/docs/6.x/validation#rule-exists

2021-12-29 09:59 UTC, warlof commented on src/resources/views/operation/modals/create_operation.blade.php
> +                                @php
instead injecting raw php, you can use blade syntax as bellow, making it more readable :

```
@if($channel->id == setting('kassie.calendar.slack_integration_default_channel', true))
<option value="{{ $channel->id }}" selected>{{ $channel->name }}</option>
@else
<option value="{{ $channel->id }}">{{ $channel->name }}</option>
@endif

2021-12-29 09:59 UTC, warlof commented on src/resources/views/setting/includes/slack.blade.php
> +                            @php
same as other, instead injecting raw, you can use blade syntax.

2021-12-31 17:38 UTC, alkari-verende commented
@warlof Thanks for the feedback! I have made the requested changes.

2021-12-31 18:27 UTC, merged